name: woosignal_shopify_example
description: API explorer demo for the woosignal_shopify_api plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  woosignal_shopify_api:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
