name: woosignal_shopify_example
description: Demonstrates how to use the woosignal plugin.

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  woosignal_shopify:
    path: ../
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
