name: woosignal_shopify_api
description: Shopify API for Dart, connect a Shopify store on WooSignal and start using the API to get products, login, create orders and more.
version: 1.0.2
homepage: https://woosignal.com
repository: https://github.com/woosignal/flutter-shopify-api
issue_tracker: https://github.com/woosignal/flutter-shopify-api/issues
documentation: https://woosignal.com/docs/api/shopify/1.0/overview

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  nylo_framework: ^5.20.18
  device_meta: ^1.1.7
  collection: ^1.18.0
  encrypt: ^5.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.1

screenshots:
  - description: The WooSignal package logo.
    path: screenshots/logo.png