name: woosignal_shopify
description: Shopify REST API for dart, connect a Shopify store and start developing with our interface for their API endpoints.
version: 1.0.0
homepage: https://woosignal.com
repository: https://github.com/woosignal/flutter-shopify-api
issue_tracker: https://github.com/woosignal/flutter-shopify-api/issues
documentation: https://woosignal.com/docs/api/shopify/1.0/overview

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.2.1+1
  device_info_plus: ^9.0.2
  shared_preferences: ^2.2.0
  encrypt: ^5.0.1
  uuid: ^3.0.6

  flutter:
    sdk: flutter
  test: ^1.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1

screenshots:
  - description: The WooSignal package logo.
    path: screenshots/logo.png